name: ocean_conservation_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
      sdk: flutter
  flutter_launcher_icons: "^0.10.0"
  cloud_firestore: ^3.5.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.11.2  
  ionicons: ^0.1.2
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.5
  get: ^4.6.5
  animated_theme_switcher: ^2.0.6
  font_awesome_flutter: ^10.2.1
  flutter_rating_bar: ^4.0.1
  mask_text_input_formatter: ^2.0.0
  flutter_credit_card: ^3.0.4
  image_cropper: ^3.0.0
  image_picker: ^0.8.6
  hexcolor: ^2.0.4
  otp_text_field: ^1.1.1
  video_player: ^2.4.7
  flutter_native_splash: ^2.2.6
  get_storage: ^2.0.3
  equatable: ^2.0.3
  flutter_easyloading: ^3.0.5
  dotted_border: ^2.0.0+2
  step_progress_indicator: ^1.0.2
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  rename: ^2.0.1
  firebase_storage: ^10.3.11
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.4.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400

  assets:
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/icons/
    - assets/pics/
    - assets/hotel/
    - assets/introduction_animation/
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
